import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../../');
const publicDir = path.join(rootDir, 'public');
const archivesDir = path.join(rootDir, 'archives');

// Historical milestone commits for retroactive backfill
const HISTORICAL_SNAPSHOTS = [
    { month: '2026-05', commit: '9ccc94e', date: '2026-05-31', description: 'End of May 2026 Snapshot' },
    { month: '2026-06', commit: 'c3b985b', date: '2026-06-30', description: 'End of June 2026 Snapshot' },
    { month: '2026-07', commit: '7555ce8', date: '2026-07-31', description: 'End of July 2026 Snapshot' },
    { month: '2026-08', commit: '4b6d957', date: '2026-08-31', description: 'End of August 2026 Snapshot' }
];

// CLI Arguments parsing
const args = process.argv.slice(2);
let targetMonth = '';
let isBackfill = false;

for (let i = 0; i < args.length; i++) {
    if (args[i] === '--month' && args[i + 1]) {
        targetMonth = args[++i].trim();
    } else if (args[i] === '--backfill') {
        isBackfill = true;
    }
}

/**
 * Determine the default target month:
 * If executed on the 1st day of the month (e.g. Oct 1st via cron),
 * defaults to the month that just ended (e.g. September).
 * Otherwise, defaults to the current month.
 */
function getDefaultMonth() {
    const now = new Date();
    if (now.getDate() === 1) {
        // Step back one day to capture the concluding month
        const prevMonthDate = new Date(now.getFullYear(), now.getMonth() - 1, 1);
        const y = prevMonthDate.getFullYear();
        const m = String(prevMonthDate.getMonth() + 1).padStart(2, '0');
        return `${y}-${m}`;
    }
    const y = now.getFullYear();
    const m = String(now.getMonth() + 1).padStart(2, '0');
    return `${y}-${m}`;
}

/**
 * Copies current public/*.json files to archives/YYYY-MM/
 */
function archiveCurrentPublic(month) {
    console.log(`\n📦 Archiving current 'public/' lists into archives/${month}...`);
    const targetDir = path.join(archivesDir, month);
    if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
    }

    if (!fs.existsSync(publicDir)) {
        console.error(`Error: ${publicDir} does not exist.`);
        return 0;
    }

    const files = fs.readdirSync(publicDir).filter(f => f.endsWith('.json'));
    let copied = 0;

    for (const file of files) {
        const srcPath = path.join(publicDir, file);
        const destPath = path.join(targetDir, file);
        fs.copyFileSync(srcPath, destPath);
        copied++;
    }

    console.log(`✅ Successfully archived ${copied} lists to archives/${month}/`);
    return copied;
}

/**
 * Backfills a historical snapshot from a specific git commit
 */
function backfillFromGit(item) {
    const { month, commit, date, description } = item;
    console.log(`\n⏳ Backfilling historical snapshot: ${month} from commit ${commit} (${date} - ${description})...`);
    const targetDir = path.join(archivesDir, month);
    if (!fs.existsSync(targetDir)) {
        fs.mkdirSync(targetDir, { recursive: true });
    }

    try {
        const treeOutput = execSync(`git --no-pager ls-tree -r --name-only ${commit} public/`, {
            cwd: rootDir,
            encoding: 'utf8'
        });

        const files = treeOutput
            .split(/\r?\n/)
            .map(line => line.trim())
            .filter(line => line.startsWith('public/') && line.endsWith('.json'));

        let extracted = 0;
        for (const gitFilePath of files) {
            const basename = path.basename(gitFilePath);
            const content = execSync(`git --no-pager show ${commit}:${gitFilePath}`, {
                cwd: rootDir,
                maxBuffer: 50 * 1024 * 1024 // 50MB buffer
            });
            fs.writeFileSync(path.join(targetDir, basename), content);
            extracted++;
        }

        console.log(`✅ Extracted ${extracted} lists for archives/${month}/ from commit ${commit}`);
        return extracted;
    } catch (err) {
        console.error(`❌ Failed to backfill for ${month} (${commit}):`, err.message);
        return 0;
    }
}

/**
 * Rebuilds archives/README.md cataloging all available archives
 */
function updateArchivesReadme() {
    if (!fs.existsSync(archivesDir)) {
        return;
    }

    const entries = fs.readdirSync(archivesDir, { withFileTypes: true })
        .filter(e => e.isDirectory() && /^\d{4}-\d{2}$/.test(e.name))
        .map(e => e.name)
        .sort()
        .reverse();

    let md = `# 🏛️ Monthly Lists Archive\n\n`;
    md += `This directory preserves monthly point-in-time snapshots of all Letterboxd Radarr lists generated by this repository.\n\n`;
    md += `A dedicated GitHub Actions workflow runs on the 1st of every month to capture the final state of all lists.\n\n`;
    md += `### Available Monthly Snapshots\n\n`;
    md += `| Month | Total Lists | Direct Directory Link | Example JSON Endpoint |\n`;
    md += `| :--- | :--- | :--- | :--- |\n`;

    for (const month of entries) {
        const monthDir = path.join(archivesDir, month);
        const files = fs.readdirSync(monthDir).filter(f => f.endsWith('.json'));
        const exampleFile = files.find(f => f.includes('top-500')) || files[0] || 'list.json';
        const pagesUrl = `https://sternpaul.github.io/letterboxd-lists/archives/${month}/${exampleFile}`;
        md += `| **${month}** | ${files.length} lists | [Browse ${month}](./${month}/) | [\`${exampleFile}\`](${pagesUrl}) |\n`;
    }

    md += `\n---\n`;
    md += `*Generated automatically by \`src/scraper/archive_monthly.mjs\`.* \n`;

    fs.writeFileSync(path.join(archivesDir, 'README.md'), md, 'utf8');
    console.log(`\n📋 Updated archives/README.md catalog with ${entries.length} monthly snapshots.`);
}

async function main() {
    console.log(`======================================================`);
    console.log(`🏛️  Monthly Lists Archive Dispatcher`);
    console.log(`======================================================`);

    if (!fs.existsSync(archivesDir)) {
        fs.mkdirSync(archivesDir, { recursive: true });
    }

    if (isBackfill) {
        console.log(`Mode: RETROACTIVE BACKFILL FROM GIT HISTORY`);
        for (const item of HISTORICAL_SNAPSHOTS) {
            backfillFromGit(item);
        }
        // Also archive current state as current month
        const currentMonth = getDefaultMonth();
        archiveCurrentPublic(currentMonth);
    } else {
        const monthToArchive = targetMonth || getDefaultMonth();
        console.log(`Target Month: ${monthToArchive}`);
        archiveCurrentPublic(monthToArchive);
    }

    updateArchivesReadme();
    console.log(`\n🎉 Monthly archive processing complete!`);
    console.log(`======================================================\n`);
}

main().catch(err => {
    console.error('Fatal error in archive_monthly:', err);
    process.exit(1);
});
