name: Update Radarr Lists
on:
  schedule:
    - cron: "0 0 * * 0" 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Fetch and filter lists
        run: |
          cd src/scraper
          npm install
          mkdir -p ../../public
          node fetch_list.mjs official/list/top-100-french-films/ ../../public/top-100-french-films-top50.json 50
          node fetch_list.mjs official/list/top-100-anime-films/ ../../public/top-100-anime-films-top50.json 50
          node fetch_list.mjs gubarenko/list/the-bfi-100-british-films/ ../../public/the-bfi-100-british-films.json
          node fetch_list.mjs official/list/top-100-best-picture-nominees-with-the-most/ ../../public/top-100-best-picture-nominees-with-the-most.json
          node fetch_list.mjs official/list/top-250-films-with-the-most-fans/ ../../public/top-250-films-with-the-most-fans.json
          node fetch_list.mjs official/list/letterboxds-top-500-films/ ../../public/letterboxds-top-500-films.json
          node fetch_list.mjs sternpaul/watchlist/ ../../public/sternpaul-watchlist.json
          node fetch_list.mjs official/list/top-100-german-films/ ../../public/top-100-german-films.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -f public/*.json
          git commit -m "Update movie lists" || exit 0
          git pull --rebase
          git push

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
